// GENERATED by scripts/sync-assets.mjs — do not edit by hand.
// Run `npm run sync:assets` after adding files to the asset drop folder.

/** Path to the primary logo. Falls back to the SVG placeholder. */
export const LOGO_SRC = "/images/brand/logo-primary.png";

/** True when LOGO_SRC is the real artwork rather than the placeholder. */
export const HAS_REAL_LOGO = true;

/** Square icon mark, for the favicon and compact placements. */
export const ICON_SRC = "/images/brand/logo-icon.png";

/** Founder portrait. Null renders a monogram placeholder instead. */
export const FOUNDER_SRC = "/images/team/founder.jpg";

/** Hero background. Null renders the brand gradient instead. */
export const HERO_SRC = null;

export const PROPERTY_IMAGES = [];
export const PROJECT_IMAGES = [];
