import Image from "next/image";
import { cn } from "@/lib/utils";
import { LOGO_SRC } from "@/lib/brand-assets.generated";
import { siteConfig } from "@/lib/site-config";

interface BrandLogoProps {
  className?: string;
  /** Renders the wordmark in white for use on dark/scrimmed backgrounds. */
  inverted?: boolean;
  priority?: boolean;
}

/**
 * The logo lockup.
 *
 * `LOGO_SRC` is generated by `npm run sync:assets` and points at the real
 * artwork once it exists, or the SVG placeholder until then.
 *
 * On `inverted`, the mark is knocked out to solid white. The brand sheet
 * sanctions a monochrome variation, so this is a permitted treatment rather
 * than the forbidden "do not change colour" case — but it is an approximation
 * of it. If a proper monochrome/white asset exists, add it to the drop folder
 * and prefer that.
 *
 * Placement over photography still needs a scrim (see `.brand-scrim`); the
 * sheet forbids the logo on busy backgrounds regardless of treatment.
 */
export function BrandLogo({
  className,
  inverted = false,
  priority = false,
}: BrandLogoProps) {
  return (
    <span className={cn("inline-flex items-center gap-2.5", className)}>
      <Image
        src={LOGO_SRC}
        alt={`${siteConfig.name} logo`}
        width={253}
        height={141}
        priority={priority}
        className={cn(
          "h-auto w-auto object-contain",
          inverted && "brightness-0 invert",
        )}
      />
      <span className="sr-only">{siteConfig.name}</span>
    </span>
  );
}
