/**
 * Copies real brand assets out of the drop folder and into `public/`, then
 * writes a manifest telling the app which ones exist.
 *
 * Run:  npm run sync:assets
 *
 * Safe to run repeatedly. It only ever copies files IN — it never deletes
 * anything from `public/`, and it never overwrites a real asset with a
 * fallback. If the drop folder is empty, the app keeps using the SVG
 * placeholder and nothing breaks.
 */

import { existsSync, mkdirSync, copyFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, extname, basename } from "node:path";
import { homedir } from "node:os";

const DROP_DIR = process.env.DHP_ASSETS_DIR ?? join(homedir(), "dhp-assets");
const PUBLIC_DIR = join(process.cwd(), "public", "images");
const BRAND_DIR = join(PUBLIC_DIR, "brand");

const FALLBACK_LOGO = "/images/brand/logo.svg";

/** Prefer vector over raster — sharper at every size. */
const LOGO_CANDIDATES = [
  "logo-primary.svg",
  "logo-primary.png",
  "logo-primary.jpg",
];
const ICON_CANDIDATES = ["logo-icon.svg", "logo-icon.png", "logo-icon.jpg"];
const FOUNDER_CANDIDATES = ["founder.jpg", "founder.jpeg", "founder.png", "founder.webp"];
const HERO_CANDIDATES = ["hero.jpg", "hero.jpeg", "hero.png", "hero.webp"];

const IMAGE_EXTS = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif", ".svg"]);

function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

/** Copies the first candidate that exists. Returns its public path or null. */
function copyFirst(candidates, destDir, destStem) {
  for (const name of candidates) {
    const src = join(DROP_DIR, name);
    if (!existsSync(src)) continue;

    const ext = extname(name);
    const destName = `${destStem}${ext}`;
    ensureDir(destDir);
    copyFileSync(src, join(destDir, destName));

    const publicPath = join(destDir, destName)
      .replace(join(process.cwd(), "public"), "")
      .split("\\")
      .join("/");

    console.log(`  ✓ ${name}  →  ${publicPath}`);
    return publicPath;
  }
  return null;
}

/** Copies every image in a subfolder. Returns the public paths. */
function copyFolder(subfolder) {
  const src = join(DROP_DIR, subfolder);
  if (!existsSync(src)) return [];

  const dest = join(PUBLIC_DIR, subfolder);
  ensureDir(dest);

  const copied = [];
  for (const file of readdirSync(src)) {
    if (!IMAGE_EXTS.has(extname(file).toLowerCase())) continue;
    copyFileSync(join(src, file), join(dest, file));
    copied.push(`/images/${subfolder}/${file}`);
  }

  if (copied.length) console.log(`  ✓ ${subfolder}/ — ${copied.length} image(s)`);
  return copied;
}

console.log(`\nSyncing brand assets from: ${DROP_DIR}\n`);

if (!existsSync(DROP_DIR)) {
  console.log(`  Drop folder not found. Using fallbacks — the site still runs.`);
  console.log(`  Create ${DROP_DIR} and add your logo/photos, then re-run.\n`);
}

ensureDir(BRAND_DIR);

const logo = copyFirst(LOGO_CANDIDATES, BRAND_DIR, "logo-primary");
const icon = copyFirst(ICON_CANDIDATES, BRAND_DIR, "logo-icon");
const founder = copyFirst(FOUNDER_CANDIDATES, join(PUBLIC_DIR, "team"), "founder");
const hero = copyFirst(HERO_CANDIDATES, join(PUBLIC_DIR, "hero"), "hero");

const propertyImages = copyFolder("properties");
const projectImages = copyFolder("projects");

const manifest = `// GENERATED by scripts/sync-assets.mjs — do not edit by hand.
// Run \`npm run sync:assets\` after adding files to the asset drop folder.

/** Path to the primary logo. Falls back to the SVG placeholder. */
export const LOGO_SRC = ${JSON.stringify(logo ?? FALLBACK_LOGO)};

/** True when LOGO_SRC is the real artwork rather than the placeholder. */
export const HAS_REAL_LOGO = ${Boolean(logo)};

/** Square icon mark, for the favicon and compact placements. */
export const ICON_SRC = ${JSON.stringify(icon ?? FALLBACK_LOGO)};

/** Founder portrait. Null renders a monogram placeholder instead. */
export const FOUNDER_SRC = ${JSON.stringify(founder)};

/** Hero background. Null renders the brand gradient instead. */
export const HERO_SRC = ${JSON.stringify(hero)};

export const PROPERTY_IMAGES = ${JSON.stringify(propertyImages, null, 2)};
export const PROJECT_IMAGES = ${JSON.stringify(projectImages, null, 2)};
`;

writeFileSync(join(process.cwd(), "src", "lib", "brand-assets.generated.ts"), manifest);

const found = [logo, icon, founder, hero].filter(Boolean).length;
console.log(
  found
    ? `\nDone — ${found} brand asset(s) wired in.\n`
    : `\nNo assets found. Placeholders remain in use; nothing is broken.\n`,
);
